language: java
scala:
- 2.11.8
script: cd rest-server && sbt compile
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - semen@actionml.com
jdk:
- oraclejdk8
env:
  global:
  - secure: VBF5IYlMoZ/vOSrShJKNFhwYjuG+DJWruN9ANoAlTQP9NbkK7ZWEn6WLAKT0xJP1If+Sm0nKRK5lqlPMWMJjkU+pzu3h762OVqofh5UAtwnxQI3l+xpKkISJOWE+IqFDAfLAZLYjUhS7gOJM29g6iSuUfz/9l3xMjfRqGr6sCr1r90TOkCLvSig1JgUPmAskRr3UFrkHvAbJyNZjVFU+ODH0JOxCoxLTpMo/EKwoduLjXiNZIEHcc3SbwpjI4XKPL7VFDSXxBfbGFExTNoRO4Z6aGC5TZUKGF4NbmFYRgDNPf2Qf5gN8V/wZ6dcSvQh1UWwZvmuIuNuqu3KJ+1HHNXl9kxWr605kD5cYBhXCT/t9Edi1zwds4BupfNcSjWgxaqi9SlzZqwLbeqXKVfupW1LggIRnN9bwmktxSGEUSlTOMcdGyc7evZ5VRaBXG7HWKK9Mi2VfnrFycV/N8Xbin6vVDpchHZjGdpxR1EMgkQJECdBcJlmw6xXlHtqHywuZ8yDpdpP03Z634EuN44fnRcBISupgGG+TYhz+sevQjPzviJMtQPWmTsQrHPGjIY2G5mImQt17GuA/Vdgnf2BSQTTYRAOMz7BrRI/jUjirBG17HY7gTi9Hqf5qGBgvHJslxvsxCC+gUfT7ZzVxPmi1USdgp3P7QDr++pB+rCeOd3E=
