version: '3'
services:
  harness:
    restart: always
    image: actionml/harness:latest
    container_name: harness
    ports:
      - "9090:9090"
    environment:
      MONGO_URI: mongodb://mongo:27017
      HARNESS_URI: http://0.0.0.0:9090
      ELASTICSEARCH_URI: http://elasticsearch:9200
      HARNESS_MAX_REQUESTS: 16
      HARNESS_MAX_CONNECTIONS: 1024
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - ${HARNESS_LOGS}:/harness/logs
      - ${HARNESS_DATA}:/data
      
  mongo:
    restart: always
    image: mongo:4.2
    container_name: mongo
    command: --logappend --logpath=/tmp/mongod.log
    ports:
      - "27017:27017"
    volumes:
      - ${MONGO_LOGS}:/logs
      - ${MONGO_DATA}:/data/db

  elasticsearch:
    restart: always
    image: elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
      discovery.seed_hosts: elasticsearch
      discovery.type: single-node
    ports:
      - "9200:9200"

  harness-cli:
    restart: always
    image: actionml/harness-cli:develop
    container_name: harness-cli
    environment:
        HARNESS_SERVER_ADDRESS: harness
    volumes:
    - ${HARNESS_DATA}:/data
